# Generated by Django 2.0.2 on 2018-02-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='create_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
