# Generated by Django 2.0.2 on 2018-02-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20180224_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='create_time',
            field=models.PositiveIntegerField(default=0, help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.PositiveIntegerField(help_text='主键', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(help_text='名称', max_length=32),
        ),
    ]
