# Generated by Django 2.0.2 on 2018-02-26 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_auto_20180226_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='update_time',
        ),
    ]
