# Generated by Django 2.0.2 on 2018-02-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_remove_admin_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(default='', max_length=32),
        ),
    ]
