# Generated by Django 2.0.2 on 2018-02-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_auto_20180226_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id,haha'),
        ),
    ]
