# Generated by Django 2.0.2 on 2018-02-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_auto_20180226_1107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin2',
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=32),
        ),
    ]
