# Generated by Django 2.0.2 on 2018-02-26 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_auto_20180226_1123'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='python_admin',
        ),
        migrations.AlterModelTable(
            name='article',
            table='python_article',
        ),
        migrations.AlterModelTable(
            name='articletag',
            table='python_article_tag',
        ),
        migrations.AlterModelTable(
            name='category',
            table='python_category',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='python_tag',
        ),
    ]
