# Generated by Django 2.0.2 on 2018-02-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_auto_20180226_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category_id',
            field=models.IntegerField(default=0, verbose_name='分类id'),
        ),
        migrations.AddField(
            model_name='article',
            name='click_number',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.IntegerField(default=0, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='articletag',
            name='article_id',
            field=models.IntegerField(default=0, verbose_name='文章id'),
        ),
        migrations.AddField(
            model_name='articletag',
            name='tag_id',
            field=models.IntegerField(default=0, verbose_name='标签id'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=64, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(max_length=128, verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(max_length=32, verbose_name='状态，1：正常，0：隐藏'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(max_length=128, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=32, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=32, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=32, verbose_name='标签名称'),
        ),
    ]
